// Presentation-only translations. Frozen Python rules and weights stay intact.
export const translations = {
  'lang="zh-CN"': 'lang="en"',
  '准备你的第一支队伍': 'Build your first team',
  '正在加载规则和模型。首次打开需要下载浏览器运行环境…': 'Loading rules and model. The first visit downloads the browser runtime…',
  '加载浏览器运行环境…首次打开稍慢，之后会使用浏览器缓存。': 'Loading the browser runtime… The first visit takes longer; later visits use the cache.',
  '加载 NumPy 与冻结模型权重…': 'Loading NumPy and the frozen model weights…',
  '无法读取模型清单': 'Could not read the model manifest',
  '未知模型文件': 'Unknown model file',
  '模型文件下载失败：': 'Model download failed: ',
  '模型完整性检查失败：': 'Model integrity check failed: ',
  '。请重新加载页面。': '. Please reload the page.',
  '浏览器运行环境启动失败。请确认网络能连接 jsDelivr，或使用较新的浏览器。': 'The browser runtime failed to start. Check access to jsDelivr or try a newer browser.',
  ' 若无法恢复，请重新加载页面；原训练模型不受影响。': ' If this persists, reload the page. The original trained model is unaffected.',
  '重新开一局': 'New game',
  '你的队伍': 'Your team',
  '← 最先出战': '← Front of team',
  '刷新 · 1 金币': 'Roll · 1 gold',
  '刷新商店 · 1 金币': 'Roll shop · 1 gold',
  '结束回合 → 战斗': 'End turn → Battle',
  '模型 A': 'Model A',
  '独立商店，不看你的当前队伍。战斗开始后揭晓。': 'Separate shop; the bot cannot see your current team. Revealed at battle.',
  '下一回合 →': 'Next round →',
  '回到战斗开始': 'Back to battle start',
  '上一步': 'Previous step',
  '下一步': 'Next step',
  '▶ 播放': '▶ Play',
  'Ⅱ 暂停': 'Ⅱ Pause',
  '战斗进度': 'Battle progress',
  '画面来自真实战斗状态快照，永久队伍不会因战斗受伤。可暂停、逐步查看。': 'Replay of actual battle states. Battle damage does not change your permanent team. Pause or step through the fight.',
  '选择一个宠物或食物': 'Select a pet or food',
  '点击商店卡片购买；食物和合成会让你选择目标。点击队伍卡片可以卖出、换位或合成。': 'Select a shop card to buy it, or choose a target for food and merging. Select a team pet to sell, swap or merge.',
  '对战规则与模型': 'Rules and model',
  '双方从 5 点生命、10 金币开始，用各自独立的商店。输一场扣 1 点生命，平局不扣；第 3 回合最多回复 1 点生命。任一方生命归零或达到 10 胜，整局结束。': 'Both sides start with 5 lives, 10 gold and separate shops. A loss costs 1 life; a draw costs none. Round 3 restores up to 1 life. The match ends when either side has no lives or reaches 10 wins.',
  '每回合最多 30 个购物动作，达到上限强制战斗；整局最多 40 回合，届时记为上限结束，不算获胜。': 'Each shop allows 30 actions before battle is forced. Matches end after at most 40 rounds; reaching that limit is not a win.',
  '模型 A（85101）：原检查点的 341,516 个参数，不再训练。浏览器里运行同一套规则与合法动作 mask，选概率最高的动作。CPU 即可。': 'Model A (85101): 341,516 frozen parameters. The browser uses the same rules and legal-action mask, choosing the highest-probability move. No GPU or further training is needed.',
  '这是冻结的 0.46 版规则沙盒，不是官方客户端。连续与你交手是新的对战模式，之前 82.27% 是三个模型平均的对手池十胜率，不是对你的胜率。': 'This is a frozen v0.46-inspired sandbox, not the official client. Direct duels differ from the benchmark: 82.27% was the three-model mean ten-win episode success against opponent pools, not a human win rate.',
  '当前对局只留在此页面，刷新会丢失。AI 当前商店不展示；上一轮决策可在战斗后查看。': 'The match stays in this page and is lost on refresh. The current AI shop is hidden; its previous-round decisions are revealed after battle.',
  '浏览器 Python 运行环境：Pyodide': 'Browser Python runtime: Pyodide',
  '查看模型上一轮如何买宠物': 'Inspect the bot’s last shopping round',
  '第一场战斗后显示。': 'Available after the first battle.',
  '请开启 JavaScript 以运行游戏。': 'Enable JavaScript to run the game.',
  '没有触发能力。': 'No triggered ability.',
  '完整规则参数': 'Full rule parameters',
  ' · 二选一升级奖励，买一个后另一个消失。': ' · Choose one of two level-up rewards; buying one removes the other.',
  '当前没有可执行操作。': 'No available actions for this selection.',
  '你赢下了这局！': 'You won the match!',
  '模型赢下了这局': 'The bot won the match',
  '达到 40 回合上限 · 本局结束': '40-round limit reached · Match ended',
  '可回看最后一场战斗，或重新开一局。': 'Replay the last battle or start a new game.',
  '双方使用同一场战斗的结果。看完后进入下一轮。': 'Both sides share this battle result. Continue when you are ready.',
  '选择商店卡片开始购买。模型不会看到你的当前队伍。': 'Select a shop card to start buying. The bot cannot see your current team.',
  '正在处理动作…': 'Processing action…',
  '真实战斗状态': 'Actual battle state',
  '已解锁 Tier': 'Unlocked Tier',
  '还有金币可用；结束回合后不会保留。': 'You still have gold; it does not carry over.',
  '即将达到动作上限，随后强制开战。': 'Near the action limit; battle will be forced.',
  '模型当前参战队伍 · 与你共同结算这一场战斗': 'The bot’s battle team · Same battle, opposite outcomes',
  '显示上一场揭晓的队伍；这一轮的购买暂不展示。': 'Previously revealed team. This round’s purchases stay hidden until battle.',
  '本轮你赢了': 'You won this round',
  '本轮模型获胜': 'The bot won this round',
  '本轮平局': 'This round was a draw',
  ' · 你达到动作上限': ' · You reached the action limit',
  ' · 模型达到动作上限': ' · The bot reached the action limit',
  '本局 seed：': 'Match seed: ',
  '模型 SHA：': 'Model SHA: ',
  '价值估计 ': 'Estimated return ',
  '（不是胜率）': ' (not win probability)',
  '放弃当前对局，重新开始？': 'Discard this match and start a new game?',
  '双方回合结束效果已结算 · 开始战斗': 'End-turn effects resolved · Battle begins',
  '友方被召唤': 'Friend summoned',
  '前方友方攻击': 'Friend ahead attacks',
  '前方友方阵亡': 'Friend ahead faints',
  '友方吃食物': 'Friend eats food',
  '友方阵亡': 'Friend faints',
  '买入友方': 'Friend bought',
  '使用商店食物': 'Shop food used',
  '战斗开始': 'Start of battle',
  '回合开始': 'Start of turn',
  '回合结束': 'End of turn',
  '攻击前': 'Before attack',
  '攻击后': 'After attack',
  '被召唤': 'Summoned',
  '每回合次数上限': 'Use limit per turn',
  '召唤物攻击': 'Summoned attack',
  '召唤物生命': 'Summoned health',
  '随机友方加属性': 'Buff random friends',
  '触发对象加属性': 'Buff triggering pet',
  '伤害随机敌人': 'Damage random enemies',
  '商店宠物加属性': 'Buff shop pets',
  '指定位置加属性': 'Buff position',
  '伤害生命最低的敌人': 'Damage lowest-health enemy',
  '高等级友方加属性': 'Buff high-level friends',
  '满足友方等级条件时加属性': 'Buff if a friend meets the level requirement',
  '复制前方能力': 'Copy ability ahead',
  '吞下前方宠物': 'Swallow pet ahead',
  '随机队友加属性': 'Buff random teammates',
  '所有友方加属性': 'Buff all friends',
  '最前方加属性': 'Buff front pet',
  '伤害最后方敌人': 'Damage last enemy',
  '未来商店宠物加属性': 'Buff future shop pets',
  '重复前方能力': 'Repeat ability ahead',
  '增加经验': 'Gain experience',
  '增加属性': 'Buff stats',
  '自身加属性': 'Buff self',
  '伤害后方': 'Damage behind',
  '伤害所有宠物': 'Damage all pets',
  '使目标阵亡': 'Make target faint',
  '生成食物': 'Stock food',
  '食物效果': 'Food effect',
  '附加效果': 'Perk',
  '（Lv1/2/3）': ' (Lv 1/2/3)',
  '结束回合': 'End turn',
  '刷新商店': 'Roll shop',
  '买入合成': 'Buy and merge',
  '买入并合成': 'Buy and merge',
  '合成到': 'Merge into',
  '喂给': 'Feed',
  '获得': 'Gain ',
  '生成': 'Stock ',
  '购买': 'Buy',
  '买入': 'Buy',
  '出售': 'Sell',
  '卖出': 'Sell',
  '交换': 'Swap',
  '解冻': 'Unfreeze',
  '冻结': 'Freeze',
  '合成': 'Merge',
  '升级': 'Level up',
  '阵亡': 'Faint',
  '受伤': 'Hurt',
  '击杀': 'Knock out',
  '召唤': 'Summon',
  '金币': 'gold',
  '商店': 'Shop',
  '队伍': 'Team',
  '攻击': 'Attack',
  '生命': 'Health',
  '数量': 'Count',
  '伤害': 'Damage',
  '百分比': 'Percent',
  '经验': 'Experience',
  '位置': 'Position',
  '空位': 'Empty slot',
  '奖励': 'Reward',
  '速度': 'Speed',
  '食物': 'Food',
  '战斗回放': 'Battle replay',
  '购物阶段': 'Shopping',
  '动作': 'actions',
  '第 ': 'Round ',
  ' 回合 · ': ' · ',
  ' 号位': '',
  ' 号 ': ': ',
  ' 号': '',
  '，': ', ',
  '：': ': ',
};

const entries = Object.entries(translations).sort((a,b) => b[0].length-a[0].length);
export function englishText(value) {
  let text = String(value ?? '');
  for (const [from, to] of entries) text = text.split(from).join(to);
  return text;
}
